version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=ServicioWeb
      - MYSQL_USER=apiuser
      - MYSQL_PASSWORD=apipass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=ServicioWeb;Uid=apiuser;Pwd=apipass123;
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  mysql_data: